INSERT INTO ERICSSON_USER (ID, USERNAME, PASSWORD) VALUES (-1, 'Administrator', 'admin');
INSERT INTO ERICSSON_USER (ID, USERNAME, PASSWORD) VALUES (-2, 'User', 'user');
INSERT INTO ERICSSON_TASK (ID, NAME, DONE, USER_ID) VALUES (-1, 'Angular Project', true, -1);
INSERT INTO ERICSSON_TASK (ID, NAME, DONE, USER_ID) VALUES (-2, 'Project presentation', false, -1);
INSERT INTO ERICSSON_ROLE (ID, NAME) VALUES (-1, 'ROLE_ADMIN');
INSERT INTO ERICSSON_ROLE (ID, NAME) VALUES (-2, 'ROLE_USER');
INSERT INTO ERICSSON_USER_ROLE (USER_ID, ROLE_ID) VALUES (-1, -1);
INSERT INTO ERICSSON_USER_ROLE (USER_ID, ROLE_ID) VALUES (-2, -2);